# Constants used in the algorithms

# algorithms group names
GENERATE_GRID_GROUP_NAME: str = "generate grid"
GENERATE_GRID_GROUP_ID: str = "generategrid"
UTILS_GROUP_NAME: str = "utils"
UTILS_GROUP_ID: str = "utils"
LANDSCAPE_METRICS_GROUP_NAME: str = "landscape metrics"
LANDSCAPE_METRICS_GROUP_ID: str = "landscapemetrics"
LANDSCAPE_METRICS_MULTI_GROUP_NAME: str = "landscape metrics multiple"
LANDSCAPE_METRICS_MULTI_GROUP_ID: str = "landscapemetrics_multi"
# Parameters names constants
FAST: str = "FAST"
# Input parameters names constants
INPUT_RASTER: str = "INPUT_RASTER"
INPUTS_MATRIX: str = "INPUTS_MATRIX"
INPUT_FILE_CSV: str = "INPUT_FILE_CSV"
INPUT_SHAPEFILE: str = "INPUT_SHAPEFILE"

# metrics parameters names constants
OUTPUT_FILE_PREFIX: str = "OUTPUT_FILE_PREFIX"
MIME_TYPE: str = "MIME_TYPE"
WINDOW_SHAPE: str = "WINDOW_SHAPE"
FRICTION_FILE: str = "FRICTION_FILE"
WINDOW_SIZES: str = "WINDOW_SIZES"
GRID_SIZES: str = "GRID_SIZES"
DOMAINS: str = "DOMAINS"
RASTER_FILTER: str = "RASTER_FILTER"
FILTER_VALUES: str = "FILTER_VALUES"
MAP_CSV: str = "MAP_CSV"
VALUES_MAPPING: str = "VALUES_MAPPING"
NODATA_VALUE: str = "NODATA_VALUE"
OUTPUT_CRS: str = "OUTPUT_CRS"

DISTANCE_FUNCTION: str = "DISTANCE_FUNCTION"
ANALYZE_TYPE: str = "ANALYZE_TYPE"

FIELDS: str = "FIELDS"
FIELD: str = "FIELD"

METADATA: str = "METADATA"

WIDTH: str = "WIDTH"
HEIGHT: str = "HEIGHT"
XMIN: str = "XMIN"
YMIN: str = "YMIN"
CELL_SIZE: str = "CELL_SIZE"

CLUSTER: str = "CLUSTER"
CLUSTER_DISTANCE: str = "CLUSTER_DISTANCE"
CLUSTER_TYPE: str = "CLUSTER_TYPE"
CLUSTER_FRICTION: str = "CLUSTER_FRICTION"
CLUSTER_MIN_AREA: str = "CLUSTER_MIN_AREA"
CLUSTER_DISTANCE_FILE: str = "CLUSTER_DISTANCE_FILE"

DISTANCE_MAX: str = "DISTANCE_MAX"
DISTANCE_TYPE: str = "DISTANCE_TYPE"
DISTANCE_FRICTION: str = "DISTANCE_FRICTION"
DISTANCE_VALUES: str = "DISTANCE_VALUES"

DELTA_DISPLACEMENT: str = "DELTA_DISPLACEMENT"
INTERPOLATE_VALUES_BOOL: str = "INTERPOLATE_VALUES_BOOL"

FILTER_ANALYZE: str = "FILTER_ANALYZE"
FILTER_NO_ANALYZE: str = "FILTER_NO_ANALYZE"

POINTS_FILE: str = "POINTS_FILE"
MAXIMUM_RATE_MISSING_VALUES: str = "MAXIMUM_RATE_MISSING_VALUES"
METRICS: str = "METRICS"
EXTENT: str = "EXTENT"
FILL_VALUE: str = "FILL_VALUE"
# Output parameters names constants
OUTPUT_DIR: str = "OUTPUT_DIR"
OUTPUT_WINDOWS_PATH_DIR: str = "OUTPUT_WINDOWS_PATH_DIR"
OUTPUT_RASTER: str = "OUTPUT_RASTER"
OUTPUT_CSV: str = "OUTPUT_CSV"
SAVE_PROPERTIES: str = "SAVE_PROPERTIES"
