# Constants used in the algorithms
# Algorithm is fast
FAST: str = "FAST"
# Input parameters names constants
INPUT_RASTER: str = "INPUT_RASTER"
INPUT_LAYER_RASTER: str = "INPUT_LAYER_RASTER"
INPUTS_MATRIX: str = "INPUTS_MATRIX"
INPUT_FILE_CSV: str = "INPUT_FILE_CSV"
INPUT_SHAPEFILE: str = "INPUT_SHAPEFILE"

# metrics parameters names constants
WINDOW_SHAPE: str = "WINDOW_SHAPE"
FRICTION_FILE: str = "FRICTION_FILE"
WINDOW_SIZES: str = "WINDOW_SIZES"
GRID_SIZES: str = "GRID_SIZES"
DOMAINS: str = "DOMAINS"
VALUES_RANGES: str = "VALUES_RANGES"
ASCII_FILTER: str = "ASCII_FILTER"
FILTER_VALUES: str = "FILTER_VALUES"
MAP_CSV: str = "MAP_CSV"
CHANGES: str = "CHANGES"
NODATA_VALUE: str = "NODATA_VALUE"


DISTANCE_FUNCTION: str = "DISTANCE_FUNCTION"
ANALYZE_TYPE: str = "ANALYZE_TYPE"


FIELDS: str = "FIELDS"
FIELD: str = "FIELD"

LOOKUP_TABLE: str = "LOOKUP_TABLE"
EXTENT: str = "EXTENT"

N_COLS: str = "N_COLS"
N_ROWS: str = "N_ROWS"
XLL_CORNER: str = "XLL_CORNER"
YLL_CORNER: str = "YLL_CORNER"
CELL_SIZE: str = "CELL_SIZE"

CLUSTER: str = "CLUSTER"
CLUSTER_DISTANCE: str = "CLUSTER_DISTANCE"
CLUSTER_TYPE: str = "CLUSTER_TYPE"
CLUSTER_FRICTION: str = "CLUSTER_FRICTION"
CLUSTER_MIN_AREA: str = "CLUSTER_MIN_AREA"


DISTANCE_MAX: str = "DISTANCE_MAX"
DISTANCE_TYPE: str = "DISTANCE_TYPE"
DISTANCE_FRICTION: str = "DISTANCE_FRICTION"


DELTA_DISPLACEMENT: str = "DELTA_DISPLACEMENT"
INTERPOLATE_VALUES_BOOL: str = "INTERPOLATE_VALUES_BOOL"

FILTER_ANALYZE: str = "FILTER_ANALYZE"
FILTER_NO_ANALYZE: str = "FILTER_NO_ANALYZE"

PIXELS_POINTS_SELECT: str = "PIXELS_POINTS_SELECT"
PIXELS_POINTS_FILE: str = "PIXELS_POINTS_FILE"

MAXIMUM_RATE_MISSING_VALUES: str = "MAXIMUM_RATE_MISSING_VALUES"
METRICS: str = "METRICS"
OPEN_ALL_ASC: str = "OPEN_ALL_ASC"

# Output parameters names constants
OUTPUT_DIR: str = "OUTPUT_DIR"
OUTPUT_RASTER: str = "OUTPUT_RASTER"
OUTPUT_CSV: str = "OUTPUT_CSV"
SAVE_PROPERTIES: str = "SAVE_PROPERTIES"
